# Đặt tên file: .gitpod.yml (ở thư mục gốc)
image:
  file: .gitpod.Dockerfile

# Tự động cài dependencies và build khi workspace mới
tasks:
  - init: |
      chmod +x mvnw
      ./mvnw dependency:go-offline -B
    command: ./mvnw spring-boot:run
ports:
  - port: 8080
    onOpen: open-preview
