name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Cache Maven dependencies để tăng tốc
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 3. Cài JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # 4. Build và test cùng lúc
      - name: Build & Test với Maven
        run: mvn clean verify

      # 5. Thiết lập Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 6. Đăng nhập vào registry (GitHub Container Registry ví dụ)
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7. Build và push Docker image
      - name: Build & Push Docker image
        run: |
          docker buildx build \
            --push \
            --tag ghcr.io/your-org/myapp-backend:${{ github.sha }} \
            --tag ghcr.io/your-org/myapp-backend:latest \
            .

      # 8. Deploy lên Railway
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          npm install -g railway
          railway login --apiToken $RAILWAY_TOKEN
          railway link
          railway up --environment production --detach
