@"
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: Run tests
        run: mvn test

      - name: Build Docker image
        run: docker build -t myapp-backend:latest .

      - name: Save Docker image as artifact
        run: docker save myapp-backend:latest | gzip > myapp-backend.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-backend-image
          path: myapp-backend.tar.gz
"@ | Set-Content .github\workflows\ci-cd.yml
